#!/bin/bash
cp ~/.zshenv .
cp ~/.zshrc .
cp ~/.vimrc .
cp ~/.bash_profile .
cp -a ~/.vim/. ./vim
cp -a ~/.config/fish/. ./fish
cp -a  ~/.config/powerline-shell/. ./powerline-shell

git add .
git commit -m "Updated on $(date)"
