commands = ["nvim"]
number_of_panes = 2

[gd]
session_name = "godot"
commands = ["nvim --listen /tmp/nvim.pipe"]

[js]
session_name = "frontend"
commands = ["nvim", "yarn install"]

[javascript]
number_of_panes = 3
session_name = "frontend"
commands = ["nvim", "fish", "yarn watch"]
